`timescale 1ns / 1ps
module tb_pseudo_mersenne_vectors;

    // ==========================================
    // Auto-generated by generate_vectors.py
    // Python guarantees arbitrary-precision arithmetic
    // ==========================================

    logic [511:0] data_in;
    logic [255:0] data_out;

    pseudo_mersenne dut (
        .data_in(data_in),
        .data_out(data_out)
    );

    localparam logic [255:0] PRIME_P = 256'h7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFED;

    // Edge Case: Zero
    localparam logic [511:0] IN_0  = 512'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    localparam logic [255:0] EXP_0 = 256'h0000000000000000000000000000000000000000000000000000000000000000;

    // Normal Case: Value < p
    localparam logic [511:0] IN_1  = 512'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000075BCD15;
    localparam logic [255:0] EXP_1 = 256'h00000000000000000000000000000000000000000000000000000000075BCD15;

    // Edge Case: Exactly p
    localparam logic [511:0] IN_2  = 512'h00000000000000000000000000000000000000000000000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFED;
    localparam logic [255:0] EXP_2 = 256'h0000000000000000000000000000000000000000000000000000000000000000;

    // H1 Path: 2^256 -> 38
    localparam logic [511:0] IN_3  = 512'h00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000;
    localparam logic [255:0] EXP_3 = 256'h0000000000000000000000000000000000000000000000000000000000000026;

    // Edge Case: 2p -> 0
    localparam logic [511:0] IN_4  = 512'h0000000000000000000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDA;
    localparam logic [255:0] EXP_4 = 256'h0000000000000000000000000000000000000000000000000000000000000000;

    // Edge Case: p-1 passthrough
    localparam logic [511:0] IN_5  = 512'h00000000000000000000000000000000000000000000000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEC;
    localparam logic [255:0] EXP_5 = 256'h7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEC;

    // Edge Case: Max 256-bit value
    localparam logic [511:0] IN_6  = 512'h0000000000000000000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;
    localparam logic [255:0] EXP_6 = 256'h0000000000000000000000000000000000000000000000000000000000000025;

    // Edge Case: Max 512-bit value
    localparam logic [511:0] IN_7  = 512'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;
    localparam logic [255:0] EXP_7 = 256'h00000000000000000000000000000000000000000000000000000000000005A3;

    // Stage 2 Stress: Max H2
    localparam logic [511:0] IN_8  = 512'h7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;
    localparam logic [255:0] EXP_8 = 256'h00000000000000000000000000000000000000000000000000000000000002D1;

    // Normal Case: 512-bit Hash
    localparam logic [511:0] IN_9  = 512'hA1B2C3D4E5F67890A1B2C3D4E5F67890A1B2C3D4E5F67890A1B2C3D4E5F678900987654321FEDCBA0987654321FEDCBA0987654321FEDCBA0987654321FEDCBA;
    localparam logic [255:0] EXP_9 = 256'h0A1076DD4494C2320A1076DD4494C2320A1076DD4494C2320A1076DD4494C5AA;

    task check(input [511:0] iv, input [255:0] ev, input string nm);
        data_in = iv;
        #10;
        if (data_out === ev)
            $display("[PASS] %s", nm);
        else begin
            $display("[FAIL] %s", nm);
            $display("       Input:    %h", iv);
            $display("       Expected: %h", ev);
            $display("       Got:      %h", data_out);
        end
    endtask

    initial begin
        $display("========================================");
        $display("Pseudo-Mersenne Tests (Pre-computed)");
        $display("========================================");
        check(IN_0, EXP_0, "Edge Case: Zero");
        check(IN_1, EXP_1, "Normal Case: Value < p");
        check(IN_2, EXP_2, "Edge Case: Exactly p");
        check(IN_3, EXP_3, "H1 Path: 2^256 -> 38");
        check(IN_4, EXP_4, "Edge Case: 2p -> 0");
        check(IN_5, EXP_5, "Edge Case: p-1 passthrough");
        check(IN_6, EXP_6, "Edge Case: Max 256-bit value");
        check(IN_7, EXP_7, "Edge Case: Max 512-bit value");
        check(IN_8, EXP_8, "Stage 2 Stress: Max H2");
        check(IN_9, EXP_9, "Normal Case: 512-bit Hash");
        $display("========================================");
        $display("Tests Completed");
        $display("========================================");
        $finish;
    end

endmodule
